/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.10.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as createListings from "../createListings.js";
import type * as createOrders from "../createOrders.js";
import type * as deleteListings from "../deleteListings.js";
import type * as deleteOrders from "../deleteOrders.js";
import type * as queryListings from "../queryListings.js";
import type * as queryOrders from "../queryOrders.js";
import type * as stripe from "../stripe.js";
import type * as updateListings from "../updateListings.js";
import type * as updateOrders from "../updateOrders.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  createListings: typeof createListings;
  createOrders: typeof createOrders;
  deleteListings: typeof deleteListings;
  deleteOrders: typeof deleteOrders;
  queryListings: typeof queryListings;
  queryOrders: typeof queryOrders;
  stripe: typeof stripe;
  updateListings: typeof updateListings;
  updateOrders: typeof updateOrders;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
